from mongoengine import Document, EmbeddedDocument, DynamicDocument, DynamicField, fields


class Collection(DynamicDocument):
    name = fields.StringField(required=True, unique=True)
    context = fields.DynamicField(required=True, default='http://iiif.io/api/presentation/2/context.json')
    type = fields.StringField(required=True, default='sc:Collection')
    label = fields.StringField(required=True, unique=True)
    metadata = fields.DynamicField(null=True)
    description = fields.DynamicField(null=True)
    thumbnail = fields.DynamicField(null=True)
    viewingHint = fields.DynamicField(null=True)
    navDate = fields.DateTimeField(null=True)
    license = fields.DynamicField(null=True)
    attribution = fields.DynamicField(null=True)
    logo = fields.DynamicField(null=True)
    related = fields.DynamicField(null=True)
    rendering = fields.DynamicField(null=True)
    seeAlso = fields.DynamicField(null=True)
    service = fields.DynamicField(null=True)
    within = fields.DynamicField(null=True)
    collections = fields.ListField(fields.DynamicField(null=True))
    manifests = fields.ListField(fields.DynamicField(null=True))
    members = fields.ListField(fields.DynamicField(null=True))
    first = fields.StringField(null=True)
    last = fields.StringField(null=True)
    total = fields.IntField(null=True)
    next = fields.StringField(null=True)
    prev = fields.StringField(null=True)
    startIndex = fields.IntField(null=True)